import type { CountryCode } from "@/types/vignette";

export interface CountryGuide {
  code: CountryCode;
  name: string;
  slug: string;
  summary: string;
  highlights: string[];
}

export const COUNTRY_GUIDES: CountryGuide[] = [
  {
    code: "AT",
    name: "Austria",
    slug: "austria",
    summary: "Digital and physical products with section toll caveats.",
    highlights: ["1-day product is valid same day", "Section toll routes are extra"],
  },
  {
    code: "CZ",
    name: "Czech Republic",
    slug: "czech-republic",
    summary: "Electronic system with CO2-sensitive pricing.",
    highlights: ["Plate camera enforcement", "EV exemption forms can be required"],
  },
  {
    code: "SK",
    name: "Slovakia",
    slug: "slovakia",
    summary: "Rolling 365-day logic with strong 10-day value.",
    highlights: ["1-day validity ends at midnight", "10-day often beats two 1-day purchases"],
  },
  {
    code: "HU",
    name: "Hungary",
    slug: "hungary",
    summary: "Vehicle category traps (D1 vs D2) can cause costly mistakes.",
    highlights: ["Check seat count and registration category", "County products can help corridor users"],
  },
  {
    code: "SI",
    name: "Slovenia",
    slug: "slovenia",
    summary: "2A vs 2B class is a common underpayment risk.",
    highlights: ["1.3 meter first axle rule matters", "Class 2B can cost double"],
  },
  {
    code: "CH",
    name: "Switzerland",
    slug: "switzerland",
    summary: "Annual-only product for passenger cars.",
    highlights: ["No short-term pass", "National roads usually require annual sticker"],
  },
  {
    code: "RO",
    name: "Romania",
    slug: "romania",
    summary: "Very low network pricing with separate bridge toll exceptions.",
    highlights: ["Rovinieta covers network roads", "Bridge peaj can be separate"],
  },
  {
    code: "BG",
    name: "Bulgaria",
    slug: "bulgaria",
    summary: "Unique weekend product can be best for short trips.",
    highlights: ["Weekend validity starts Friday noon", "Weekly and quarterly options available"],
  },
  {
    code: "DE",
    name: "Germany",
    slug: "germany",
    summary: "Useful baseline for routes with no passenger-car vignette.",
    highlights: ["No national passenger-car vignette", "Good baseline for comparison"],
  },
  {
    code: "HR",
    name: "Croatia",
    slug: "croatia",
    summary: "Motorway tolling is mainly distance-based for passenger cars.",
    highlights: ["No national vignette for passenger cars", "Pay motorway tolls by route usage"],
  },
  {
    code: "RS",
    name: "Serbia",
    slug: "serbia",
    summary: "Transit corridors commonly use distance-based toll plazas.",
    highlights: ["No national vignette for passenger cars", "Budget for motorway toll payments"],
  },
  {
    code: "DK",
    name: "Denmark",
    slug: "denmark",
    summary: "No national car vignette, but major bridges are tolled.",
    highlights: ["Storebaelt crossing can be tolled", "Oresund crossing to Sweden is tolled"],
  },
  {
    code: "SE",
    name: "Sweden",
    slug: "sweden",
    summary: "No national car vignette, with selected bridge or city charges.",
    highlights: ["Oresund entry from Denmark is tolled", "No country-wide passenger-car vignette"],
  },
  {
    code: "NL",
    name: "Netherlands",
    slug: "netherlands",
    summary: "No national passenger-car vignette on regular routes.",
    highlights: ["Common destination for Germany users", "Selected crossings can still have tolls"],
  },
  {
    code: "BE",
    name: "Belgium",
    slug: "belgium",
    summary: "No national passenger-car vignette on standard routes.",
    highlights: ["Frequent transit country", "Useful no-vignette baseline"],
  },
  {
    code: "FR",
    name: "France",
    slug: "france",
    summary: "Motorways are commonly distance-tolled.",
    highlights: ["No national car vignette", "Autoroute sections usually paid by distance"],
  },
  {
    code: "IT",
    name: "Italy",
    slug: "italy",
    summary: "Motorways are commonly distance-tolled.",
    highlights: ["No national car vignette", "Autostrade routes usually paid by distance"],
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    slug: "bosnia-and-herzegovina",
    summary: "Selected motorway sections are tolled.",
    highlights: ["No national car vignette", "Toll sections exist on key corridors"],
  },
  {
    code: "ME",
    name: "Montenegro",
    slug: "montenegro",
    summary: "No national vignette with selected road/tunnel tolls.",
    highlights: ["Popular destination route", "Budget for selected toll points"],
  },
  {
    code: "XK",
    name: "Kosovo",
    slug: "kosovo",
    summary: "No standard national passenger-car vignette.",
    highlights: ["Useful for Balkans route planning", "Check local road and border rules separately"],
  },
  {
    code: "MK",
    name: "North Macedonia",
    slug: "north-macedonia",
    summary: "Major corridors commonly use toll plazas.",
    highlights: ["No national vignette", "Toll plazas on motorway routes"],
  },
  {
    code: "AL",
    name: "Albania",
    slug: "albania",
    summary: "No national vignette with selected tolled corridors.",
    highlights: ["No country-wide vignette", "Certain motorway routes can be tolled"],
  },
  {
    code: "PL",
    name: "Poland",
    slug: "poland",
    summary: "No national car vignette, with selected tolled motorway sections.",
    highlights: ["Common route from Germany", "Selected motorway stretches are tolled"],
  },
  {
    code: "ES",
    name: "Spain",
    slug: "spain",
    summary: "No national car vignette; selected autopista corridors are tolled.",
    highlights: ["No country-wide vignette", "Some major autopista routes use tolls"],
  },
  {
    code: "PT",
    name: "Portugal",
    slug: "portugal",
    summary: "No national car vignette; electronic tolling is used on selected motorways.",
    highlights: ["No country-wide vignette", "Electronic toll systems can apply"],
  },
  {
    code: "GB",
    name: "United Kingdom",
    slug: "united-kingdom",
    summary: "No national passenger-car vignette with selected toll roads and crossings.",
    highlights: ["Dartford and other crossings may require payment", "No country-wide passenger-car vignette"],
  },
  {
    code: "IE",
    name: "Ireland",
    slug: "ireland",
    summary: "No national passenger-car vignette with selected motorway toll systems.",
    highlights: ["eFlow tolling on selected routes", "No country-wide passenger-car vignette"],
  },
  {
    code: "TR",
    name: "Turkey",
    slug: "turkey",
    summary: "Motorways and bridges commonly use HGS or OGS toll systems.",
    highlights: ["No national passenger-car vignette", "HGS/OGS setup is important for frequent travel"],
  },
  {
    code: "GR",
    name: "Greece",
    slug: "greece",
    summary: "Major motorway corridors commonly use toll plazas.",
    highlights: ["No country-wide passenger-car vignette", "Plan for motorway toll booths"],
  },
];
