import type { CountryCode } from "@/types/vignette";

export const OFFICIAL_LINKS: Record<CountryCode, string> = {
  DE: "https://www.balm.bund.de/",
  AT: "https://shop.asfinag.at/",
  CZ: "https://edalnice.cz/",
  SK: "https://eznamka.sk/",
  HU: "https://ematrica.nemzetiutdij.hu/",
  SI: "https://evinjeta.dars.si/",
  CH: "https://via.admin.ch/",
  RO: "https://www.rovinieta.ro/",
  BG: "https://www.bgtoll.bg/",
  HR: "https://www.hac.hr/en/toll",
  RS: "https://www.putevi-srbije.rs/",
  DK: "https://www.sundogbaelt.dk/en/",
  SE: "https://www.transportstyrelsen.se/en/road/vehicles/",
  NL: "https://www.government.nl/topics/mobility-public-transport-and-road-safety",
  BE: "https://mobilit.belgium.be/en/road",
  FR: "https://www.service-public.fr/particuliers/vosdroits/F2796",
  IT: "https://www.autostrade.it/",
  BA: "https://jpautoceste.ba/en/",
  ME: "https://www.gov.me/en/transport",
  XK: "https://rks-gov.net/en/",
  MK: "https://roads.org.mk/en/",
  AL: "https://arrsh.gov.al/en/",
  PL: "https://www.gov.pl/web/infrastructure",
  ES: "https://www.mitma.gob.es/",
  PT: "https://www.portugaltolls.com/en",
  GB: "https://www.gov.uk/browse/driving",
  IE: "https://www.gov.ie/en/campaigns/2f7f4-road-safety-and-transport/",
  TR: "https://www.kgm.gov.tr/",
  GR: "https://www.gov.gr/en/ipiresies/polites-kai-kathemerinoteta/metakineseis",
};

export const SECTION_TOLL_LINKS: Partial<Record<CountryCode, string>> = {
  AT: "https://shop.asfinag.at/en/toll-calculator/route-toll/",
  RO: "https://www.cnadnr.ro/en/peage",
  DK: "https://www.oresundsbron.com/en/prices",
  SE: "https://www.oresundsbron.com/en/prices",
  HR: "https://www.hac.hr/en/toll",
  RS: "https://www.putevi-srbije.rs/index.php/en/toll",
  FR: "https://www.autoroutes.fr/en",
  IT: "https://www.autostrade.it/en/home",
  BA: "https://jpautoceste.ba/en/toll-collection-system",
  ME: "https://www.gov.me/en/transport",
  MK: "https://roads.org.mk/en/toll-collection",
  AL: "https://arrsh.gov.al/en/",
  PL: "https://www.gov.pl/web/infrastructure",
  ES: "https://www.autopistas.com/en/toll-calculator",
  PT: "https://www.portugaltolls.com/en",
  GB: "https://www.gov.uk/pay-dartford-crossing-charge",
  IE: "https://www.eflow.ie/",
  TR: "https://www.kgm.gov.tr/Sayfalar/KGM/SiteTr/Otoyollar/UcretlerveGecisler.aspx",
  GR: "https://www.gefyra.gr/en/tolls/",
};
