import type { CountryPricing } from "@/types/vignette";

export const PRICE_LAST_VERIFIED_AT = "2026-02-10";

export const PRICING_2026: Record<string, CountryPricing> = {
  AT: {
    countryCode: "AT",
    countryName: "Austria",
    products: [
      {
        id: "1d_car",
        label: "1-Day (Car)",
        price: 9.6,
        currency: "EUR",
        notes: "Valid until 23:59.",
        vehicleTags: ["PASSENGER_CAR_M1", "VAN_OR_MPV"],
      },
      { id: "10d_car", label: "10-Day (Car)", price: 12.8, currency: "EUR", vehicleTags: ["PASSENGER_CAR_M1", "VAN_OR_MPV"] },
      { id: "2m_car", label: "2-Month (Car)", price: 32.0, currency: "EUR", vehicleTags: ["PASSENGER_CAR_M1", "VAN_OR_MPV"] },
      { id: "annual_car", label: "Annual (Car)", price: 106.8, currency: "EUR", vehicleTags: ["PASSENGER_CAR_M1", "VAN_OR_MPV"] },
      { id: "1d_moto", label: "1-Day (Motorcycle)", price: 3.8, currency: "EUR", vehicleTags: ["MOTORCYCLE"] },
      { id: "10d_moto", label: "10-Day (Motorcycle)", price: 5.1, currency: "EUR", vehicleTags: ["MOTORCYCLE"] },
      { id: "2m_moto", label: "2-Month (Motorcycle)", price: 12.8, currency: "EUR", vehicleTags: ["MOTORCYCLE"] },
      { id: "annual_moto", label: "Annual (Motorcycle)", price: 42.7, currency: "EUR", vehicleTags: ["MOTORCYCLE"] },
    ],
    caveats: [
      "Digital 2-month and annual products can be delayed by withdrawal rules in some purchase flows.",
      "Separate section tolls may apply for crossings like Brenner or Tauern.",
    ],
  },
  CZ: {
    countryCode: "CZ",
    countryName: "Czech Republic",
    products: [
      { id: "1d_std", label: "1-Day (Standard fuel)", price: 230, currency: "CZK" },
      { id: "10d_std", label: "10-Day (Standard fuel)", price: 300, currency: "CZK" },
      { id: "30d_std", label: "30-Day (Standard fuel)", price: 480, currency: "CZK" },
      { id: "annual_std", label: "Annual (Standard fuel)", price: 2570, currency: "CZK" },
    ],
    caveats: ["EV exemptions may require a pre-submitted notice for foreign vehicles."],
  },
  SK: {
    countryCode: "SK",
    countryName: "Slovakia",
    products: [
      { id: "1d", label: "1-Day", price: 8.1, currency: "EUR", notes: "Valid until midnight." },
      { id: "10d", label: "10-Day", price: 10.8, currency: "EUR" },
      { id: "30d", label: "30-Day", price: 17.1, currency: "EUR" },
      { id: "365d", label: "365-Day", price: 90, currency: "EUR" },
    ],
    caveats: ["Two 1-day passes can cost more than one 10-day pass."],
  },
  HU: {
    countryCode: "HU",
    countryName: "Hungary",
    products: [
      { id: "1d_d1", label: "1-Day (D1)", price: 5550, currency: "HUF", vehicleTags: ["PASSENGER_CAR_M1"] },
      { id: "10d_d1", label: "10-Day (D1)", price: 6900, currency: "HUF", vehicleTags: ["PASSENGER_CAR_M1"] },
      { id: "monthly_d1", label: "Monthly (D1)", price: 11170, currency: "HUF", vehicleTags: ["PASSENGER_CAR_M1"] },
      { id: "annual_d1", label: "Annual (D1)", price: 61760, currency: "HUF", vehicleTags: ["PASSENGER_CAR_M1"] },
      { id: "10d_d1m", label: "10-Day (D1M Motorcycle)", price: 3380, currency: "HUF", vehicleTags: ["MOTORCYCLE"] },
      { id: "annual_d1m", label: "Annual (D1M Motorcycle)", price: 26660, currency: "HUF", vehicleTags: ["MOTORCYCLE"] },
      { id: "10d_d2", label: "10-Day (D2 Van/Camper)", price: 10040, currency: "HUF", vehicleTags: ["VAN_OR_MPV", "COMMERCIAL_N1"] },
    ],
    caveats: ["Vehicles in D2 can pay much more. Check registration class and seat count."],
  },
  SI: {
    countryCode: "SI",
    countryName: "Slovenia",
    products: [
      { id: "weekly_2a", label: "Weekly (2A)", price: 16, currency: "EUR", vehicleTags: ["PASSENGER_CAR_M1"] },
      { id: "monthly_2a", label: "Monthly (2A)", price: 32, currency: "EUR", vehicleTags: ["PASSENGER_CAR_M1"] },
      { id: "annual_2a", label: "Annual (2A)", price: 117.5, currency: "EUR", vehicleTags: ["PASSENGER_CAR_M1"] },
      { id: "weekly_2b", label: "Weekly (2B Van/Camper)", price: 32, currency: "EUR", vehicleTags: ["VAN_OR_MPV", "COMMERCIAL_N1"] },
      { id: "monthly_2b", label: "Monthly (2B Van/Camper)", price: 64.1, currency: "EUR", vehicleTags: ["VAN_OR_MPV", "COMMERCIAL_N1"] },
      { id: "annual_moto", label: "Annual (Motorcycle)", price: 58.7, currency: "EUR", vehicleTags: ["MOTORCYCLE"] },
    ],
    caveats: ["Class 2B vehicles (>= 1.3m at first axle) can pay about double."],
  },
  CH: {
    countryCode: "CH",
    countryName: "Switzerland",
    products: [{ id: "annual", label: "Annual", price: 40, currency: "CHF" }],
    caveats: ["No short-term product for passenger cars."],
  },
  RO: {
    countryCode: "RO",
    countryName: "Romania",
    products: [
      { id: "1d", label: "1-Day", price: 2.5, currency: "EUR" },
      { id: "10d", label: "10-Day", price: 3.3, currency: "EUR" },
      { id: "30d", label: "30-Day", price: 5.3, currency: "EUR" },
      { id: "12m", label: "12-Month", price: 28, currency: "EUR" },
    ],
    caveats: ["Bridge tolls are separate from the rovinieta network pass."],
  },
  BG: {
    countryCode: "BG",
    countryName: "Bulgaria",
    products: [
      { id: "weekend", label: "Weekend", price: 10, currency: "BGN", notes: "Fri 12:00 to Sun 23:59." },
      { id: "weekly", label: "Weekly", price: 15, currency: "BGN" },
      { id: "quarterly", label: "Quarterly", price: 54, currency: "BGN" },
      { id: "annual", label: "Annual", price: 97, currency: "BGN" },
    ],
    caveats: ["Weekend vignette can be cheapest for short Fri-Sun trips."],
  },
  DE: {
    countryCode: "DE",
    countryName: "Germany",
    products: [],
    caveats: ["Passenger cars generally have no national vignette requirement."],
  },
  HR: {
    countryCode: "HR",
    countryName: "Croatia",
    products: [],
    caveats: ["Croatia uses distance-based motorway tolls instead of a national vignette for cars."],
  },
  RS: {
    countryCode: "RS",
    countryName: "Serbia",
    products: [],
    caveats: ["Serbia mainly uses distance-based toll plazas on major motorways."],
  },
  DK: {
    countryCode: "DK",
    countryName: "Denmark",
    products: [],
    caveats: ["No national vignette for passenger cars, but major bridges can have tolls."],
  },
  SE: {
    countryCode: "SE",
    countryName: "Sweden",
    products: [],
    caveats: ["No national vignette for passenger cars; bridge/city charges can still apply."],
  },
  NL: {
    countryCode: "NL",
    countryName: "Netherlands",
    products: [],
    caveats: ["No national passenger-car vignette; tolls may apply on selected tunnels or crossings."],
  },
  BE: {
    countryCode: "BE",
    countryName: "Belgium",
    products: [],
    caveats: ["No national passenger-car vignette on standard routes."],
  },
  FR: {
    countryCode: "FR",
    countryName: "France",
    products: [],
    caveats: ["France motorways commonly use distance-based tolls rather than a national vignette."],
  },
  IT: {
    countryCode: "IT",
    countryName: "Italy",
    products: [],
    caveats: ["Italy motorways commonly use distance-based tolls rather than a national vignette."],
  },
  BA: {
    countryCode: "BA",
    countryName: "Bosnia and Herzegovina",
    products: [],
    caveats: ["No national vignette for cars; selected motorway sections use tolls."],
  },
  ME: {
    countryCode: "ME",
    countryName: "Montenegro",
    products: [],
    caveats: ["No national vignette for cars; selected roads/tunnels may require toll payments."],
  },
  XK: {
    countryCode: "XK",
    countryName: "Kosovo",
    products: [],
    caveats: ["No standard national vignette for passenger cars."],
  },
  MK: {
    countryCode: "MK",
    countryName: "North Macedonia",
    products: [],
    caveats: ["North Macedonia commonly uses toll plazas on major motorways."],
  },
  AL: {
    countryCode: "AL",
    countryName: "Albania",
    products: [],
    caveats: ["No national vignette for passenger cars; selected corridors may be tolled."],
  },
  PL: {
    countryCode: "PL",
    countryName: "Poland",
    products: [],
    caveats: ["No national passenger-car vignette; selected motorway sections are tolled."],
  },
  ES: {
    countryCode: "ES",
    countryName: "Spain",
    products: [],
    caveats: ["No national passenger-car vignette; selected autopista corridors are tolled."],
  },
  PT: {
    countryCode: "PT",
    countryName: "Portugal",
    products: [],
    caveats: ["No national passenger-car vignette; selected motorways use electronic tolling."],
  },
  GB: {
    countryCode: "GB",
    countryName: "United Kingdom",
    products: [],
    caveats: ["No national vignette for passenger cars; selected bridges and toll roads require payment."],
  },
  IE: {
    countryCode: "IE",
    countryName: "Ireland",
    products: [],
    caveats: ["No national vignette for passenger cars; motorway toll plazas and eFlow tolling apply on selected roads."],
  },
  TR: {
    countryCode: "TR",
    countryName: "Turkey",
    products: [],
    caveats: ["Turkey uses HGS/OGS motorway and bridge toll systems instead of a national passenger-car vignette."],
  },
  GR: {
    countryCode: "GR",
    countryName: "Greece",
    products: [],
    caveats: ["No national passenger-car vignette; toll plazas are common on major motorway corridors."],
  },
};
